### PR TITLE
Upgrading requests

### PR DESCRIPTION
**Pull request by carllopez**

### CODE REVIEW

**Review by FredworkLemmas — APPROVED** [review]
didn't test, but low risk and is this in use anywhere?

**Comment by carllopez** [comment]
@FredAtLandMetrics I'm not entirely sure it's used, I've seen some collaborations from @amberylx, I'll ask her

**Comment by amberylx** [comment]
@FredAtLandMetrics @carllopez It's very lightly used in mp-internal-tools for some tests.

**Comment by carllopez** [comment]
@amberylx I'll deploy it and run the tests in `mp-internal-tools` to confirm it works

**Pull request merged**
